#!/bin/bash
#
# Auto-generated SLURM script (Python)
# Generated by: batchjobPY
#

#SBATCH --job-name=koala_job
#SBATCH --account=OD-232703
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=mathew.vickers@csiro.au
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=55:00:00
#SBATCH --mem=20G
#SBATCH --output=/scratch3/vic039/logs/koala_job_%A_%a.out
#SBATCH --error=/scratch3/vic039/logs/koala_job_%A_%a.err
#SBATCH --signal=B:TERM@120
#SBATCH --array=2010 #-2023


set -euo pipefail

# ---- Setup ------------------------------------------------------------------
# Enforce permissions (shared, auditable, admin-friendly)
source /home/vic039/repos/hpc-vscode-hack/job_preamble.sh

mkdir -p "/scratch3/vic039/logs"

# Per-job tempdir (keeps temp junk contained; cleans on normal exit)
TMPROOT="/scratch3/vic039/tmp"
JOBTMP="/scratch3/vic039/tmp/slurm_${SLURM_JOB_ID}"

mkdir -p "${JOBTMP}"

export TMPDIR="${JOBTMP}"
export TEMP="${JOBTMP}"
export TMP="${JOBTMP}"

cleanup() {
  echo "[CLEANUP] removing ${JOBTMP}"
  rm -rf "${JOBTMP}"
}
trap cleanup EXIT TERM INT HUP

# Sweep stale temp dirs (older than 7 days)
find "/scratch3/vic039/tmp" -maxdepth 1 -type d -name "slurm_*" -mtime +7 -exec rm -rf {} + || true

# Toolchain + python env
# module load python
module load rust/1.84.1
module load gdal

# Make conda available 
source /apps/miniforge3/enable_miniforge.sh
conda activate connectivity-py312
hash -r
export PATH="$CONDA_PREFIX/bin:$PATH"
unset PYTHONPATH

cd /scratch3/$USER
echo "[INFO] CONDA_PREFIX=$CONDA_PREFIX"
echo "[INFO] python=$(which python)"
python -c "import sys; print('[INFO] exe', sys.executable)"
python -c "import rust_conn; print('[INFO] rust_conn ok')"
python -c "import connectivity; print('[INFO] connectivity ok')" || true


python -c "import sys, site; print('[INFO] site-packages:', site.getsitepackages())"
python -c "import pkgutil; print('[INFO] has connectivity?', any(m.name=='connectivity' for m in pkgutil.iter_modules()))"
python -c "import pkgutil; print('[INFO] top rust-ish:', [m.name for m in pkgutil.iter_modules() if 'rust' in m.name.lower()][:20])"
python -c "import importlib.util; print('[INFO] spec connectivity:', importlib.util.find_spec('connectivity'))"


# ---- Run --------------------------------------------------------------------
YEAR="${SLURM_ARRAY_TASK_ID}"

# Sanity
echo "[INFO] YEAR=$YEAR"
echo "[INFO] python=$(which python)"
echo "[INFO] gdal_translate=$(which gdal_translate || true)"
echo "[INFO] gdaladdo=$(which gdaladdo || true)"
echo "[INFO] rustc=$(which rustc || true)"

# Avoid accidental multithreading surprises
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# Run the per-year worker
python /home/vic039/repos/connectivity/connectivity_year.py "$YEAR"
