[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "connectivity"
description = "A multi-resolution landscape connectivity algorithm written in Rust"
authors = [{ name = "Roozbeh Valavi", email = "roozbeh.valavi@csiro.au" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.23",
    "rasterio>=1.2",
    "geopandas",
    "shapely",
    "scipy",
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
[tool.maturin]
features = ["pyo3/extension-module"]
# Include all .py files in the package directory
include = ["connectivity/*.py"]

[project.urls]
Homepage = "https://github.com/csiro-internal/connectivity"
Repository = "https://github.com/csiro-internal/connectivity"
Issues = "https://github.com/csiro-internal/connectivity/issues" 