[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "connectivity"
description = "A multi-resolution landscape connectivity algorithm"
authors = [{ name = "Roozbeh Valavi", email = "roozbeh.valavi@csiro.au" }]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
[tool.maturin]
features = ["pyo3/extension-module"]
# Include all .py files in the package directory
include = ["connectivity/*.py"]