#!/bin/bash
#
# Auto-generated SLURM script (Python)
# Generated by: batchjobPY
#

#SBATCH --job-name=conn_tiles
#SBATCH --account=OD-232703
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=mathew.vickers@csiro.au
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --mem=20G
#SBATCH --output=/scratch3/vic039/logs/conn_tiles_%A_%a.out
#SBATCH --error=/scratch3/vic039/logs/conn_tiles_%A_%a.err
#SBATCH --signal=B:TERM@120
#SBATCH --array=0-44

set -euo pipefail

# ---- Setup ------------------------------------------------------------------
# Enforce permissions (shared, auditable, admin-friendly)
source /home/vic039/repos/hpc-vscode-hack/job_preamble.sh

mkdir -p "/scratch3/vic039/logs"

# Per-job tempdir (keeps temp junk contained; cleans on normal exit)
TMPROOT="/scratch3/vic039/tmp"
JOBTMP="/scratch3/vic039/tmp/slurm_${SLURM_JOB_ID}"
mkdir -p "${JOBTMP}"

export TMPDIR="${JOBTMP}"
export TEMP="${JOBTMP}"
export TMP="${JOBTMP}"

cleanup() {
  echo "[CLEANUP] removing {JOBTMP}"
  rm -rf "${JOBTMP}"
}
trap cleanup EXIT TERM INT HUP

# Sweep stale temp dirs (older than 7 days)
find "/scratch3/vic039/tmp" -maxdepth 1 -type d -name "slurm_*" -mtime +7 -exec rm -rf {} + || true

module load python

# ---- Run --------------------------------------------------------------------

python /home/vic039/repos/connectivity/run_tile_connectedness.py

# End of file
