#!/bin/bash
#
# Auto-generated SLURM script (Python)
# Generated by: batchjobPY
#

#SBATCH --job-name=conn_tiles
#SBATCH --account=OD-232703
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=mathew.vickers@csiro.au
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --mem=32G
#SBATCH --output=/scratch3/vic039/logs/conn_tiles_%A_%a.out
#SBATCH --error=/scratch3/vic039/logs/conn_tiles_%A_%a.err
#SBATCH --signal=B:TERM@120
#SBATCH --array=0-629  # 0 - (Ntiles * Nyears - 1)

set -euo pipefail

# ---- Setup ------------------------------------------------------------------
# Enforce permissions (shared, auditable, admin-friendly)
source /home/vic039/repos/hpc-vscode-hack/job_preamble.sh

mkdir -p "/scratch3/vic039/logs"


module load rust/1.84.1
module load gdal
source /apps/miniforge3/enable_miniforge.sh
conda activate connectivity-py312
hash -r
export PATH="$CONDA_PREFIX/bin:$PATH"
unset PYTHONPATH

TILES_JSON="/home/vic039/repos/connectivity/tiles_core3000_buf450.json"
COND_DIR="/datasets/work/lw-nkmp/work/Koala_Habitat_Condition_Mapping_Project/Data/outputs/condition_mosaics"
OUT_BASE="/datasets/work/lw-nkmp/work/Koala_Habitat_Condition_Mapping_Project/Data/outputs/connectedness_tiles"

N_TILES=$(python -c "import json; print(len(json.load(open('$TILES_JSON'))['tiles']))")
TASK=${SLURM_ARRAY_TASK_ID}

YEAR=$((2010 + TASK / N_TILES))
TILE=$((TASK % N_TILES))

echo "[INFO] task=$TASK year=$YEAR tile=$TILE n_tiles=$N_TILES"
echo "[INFO] python=$(which python)"

python /home/vic039/repos/connectivity/run_year_tile_connectedness.py \
  "$TILES_JSON" "$YEAR" "$TILE" "$COND_DIR" "$OUT_BASE"
